global:
  resolve_timeout: 1m
route:
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'zabbix'
  routes:
    - match:
        alertname: DeadMansSwitch
      repeat_interval: 5m
      receiver: deadmansswitch
receivers:
  - name: deadmansswitch
  - name: 'zabbix'
    webhook_configs:
      - url: http://172.26.7.172:80/alerts
        send_resolved: true


